# Generated by Django 4.1.4 on 2023-02-02 04:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airconditions', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('gps', models.BooleanField(default=False)),
                ('luggage', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('seat_belt', models.BooleanField(default=False)),
                ('sleeping_bed', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('onboard_computer', models.BooleanField(default=False)),
                ('audio_input', models.BooleanField(default=False)),
                ('long_term_trips', models.BooleanField(default=False)),
                ('car_Kit', models.BooleanField(default=False)),
                ('remote_central_locking', models.BooleanField(default=False)),
                ('climate_control', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car-image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 2, 2, 10, 17, 23, 548784))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('num_of_seats', models.IntegerField()),
                ('num_of_air_bag', models.PositiveSmallIntegerField(default=0)),
                ('fuel_type', models.CharField(choices=[('P', 'Petrol')], default='P', max_length=1)),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('M', 'Menual')], default='M', max_length=1)),
                ('const_per_hour', models.PositiveIntegerField()),
                ('cost_par_day', models.PositiveIntegerField()),
                ('cost_of_leasing', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('comment', models.ManyToManyField(to='car.review')),
                ('feature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.features')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car.images')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
