# Generated by Django 4.1.4 on 2023-02-02 06:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car_location_alter_review_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.AddField(
            model_name='images',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.car'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 11, 38, 25, 888676)),
        ),
    ]
