# Generated by Django 4.1.4 on 2023-02-02 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_car_feature_features_car_alter_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='car.car'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 12, 44, 30, 230520)),
        ),
    ]
