# Generated by Django 4.1.6 on 2023-02-09 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_features_car_alter_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 9, 19, 3, 5, 480273)),
        ),
    ]
