# Generated by Django 4.1.6 on 2023-02-10 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_privatemsg_car_like_alter_review_time_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car-image/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 18, 46, 21, 638319)),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
