# Generated by Django 4.1.6 on 2023-04-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_order_status_alter_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Decliend')], default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 14, 22, 43, 24570)),
        ),
    ]
