# Generated by Django 4.1.6 on 2023-04-26 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_alter_order_status_alter_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 26, 20, 12, 55, 800362)),
        ),
    ]
